-- My Care cloud state
-- Run this file in the Supabase SQL editor.

create table if not exists public.app_states (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  revision bigint not null default 1,
  updated_at timestamptz not null default now()
);

alter table public.app_states enable row level security;

create table if not exists public.app_state_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  payload jsonb not null,
  revision bigint not null,
  saved_at timestamptz not null default now()
);

create index if not exists app_state_history_user_saved_idx
on public.app_state_history (user_id, saved_at desc);

alter table public.app_state_history enable row level security;

drop policy if exists "Users can read their own app state" on public.app_states;
create policy "Users can read their own app state"
on public.app_states for select
using (auth.uid() = user_id);

drop policy if exists "Users can create their own app state" on public.app_states;
create policy "Users can create their own app state"
on public.app_states for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own app state" on public.app_states;
create policy "Users can update their own app state"
on public.app_states for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own app state" on public.app_states;
create policy "Users can delete their own app state"
on public.app_states for delete
using (auth.uid() = user_id);

drop policy if exists "Users can read their own state history" on public.app_state_history;
create policy "Users can read their own state history"
on public.app_state_history for select
using (auth.uid() = user_id);

drop policy if exists "Users can create their own state history" on public.app_state_history;
create policy "Users can create their own state history"
on public.app_state_history for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own state history" on public.app_state_history;
create policy "Users can delete their own state history"
on public.app_state_history for delete
using (auth.uid() = user_id);

create or replace function public.archive_app_state()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  insert into public.app_state_history (user_id, payload, revision, saved_at)
  values (old.user_id, old.payload, old.revision, now());

  delete from public.app_state_history
  where user_id = old.user_id
    and id not in (
      select id
      from public.app_state_history
      where user_id = old.user_id
      order by saved_at desc, id desc
      limit 20
    );

  return old;
end;
$$;

drop trigger if exists archive_app_state_before_change on public.app_states;
create trigger archive_app_state_before_change
before update or delete on public.app_states
for each row execute function public.archive_app_state();

create or replace function public.touch_app_state()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  new.revision = old.revision + 1;
  return new;
end;
$$;

drop trigger if exists touch_app_state_before_update on public.app_states;
create trigger touch_app_state_before_update
before update on public.app_states
for each row execute function public.touch_app_state();
